controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

calendar_default:
    path: /calendar/{month}
    controller: App\Controller\CalendarController::default

calendar_weekends:
    path: /calendar/weekends/{month}
    controller: App\Controller\CalendarController::weekends

calendar_table:
    path: /calendar/table/{month}
    controller: App\Controller\CalendarController::table

